### ISSUE TITLE
Youtube playback is broken

### ISSUE THREAD

**Issue by Aasikki** [Frederikam/ukulele#10]
When I try to play anything from YouTube, the bot says "Started playing x" but I can't hear anything playing. SoundCloud works fine. I tried restarting the bot but it didn't fix it.

**Comment by CaiusAjiz** [comment]
Seem to have the same issue. Paste of what looks to be failing (it happens straight after ;p)

[pastebin](https://pastebin.com/5kd8ELYJ)

The logs that are spat out are actually longer than Pastebin allows, but I can find a way to source the rest, should it be useful. I'll have a delve a little later (as this is open source after all).

**Comment by Frederikam** [comment]
Ah, only just noticed this issue now. Please try the latest commit.

**Comment by CaiusAjiz** [comment]
Confirmed new repo and dependencies work, I was prepping a PR when you beat me to it!
