### ISSUE TITLE
Feature Request: Support Volume Control

### ISSUE THREAD

**Issue by kiloforce** [Frederikam/ukulele#2]
In my opinion, Volume Control is probably the #1 most critical feature.  If players are left to fend for themselves, they more often than not just mute it.  Even if it is limited to specific values like 5%, 10%, 50%, 25%, or very-low, low, medium, high.

**Comment by Frederikam** [comment]
Thanks for the request. This would be very easy for someone to inplement

**Comment by OtterBoops** [comment]
It would be worth noting that as discussed in the discord channel, it would be preferable to have the config persisted through restarts.

**Comment by Frederikam** [comment]
An embedded DB would be nice

**Comment by Frederikam** [comment]
Feel free to open a separate issue about persisting volume levels

**Comment by Frederikam** [comment]
The volume setting now gets saved in the new database.

The database is zero-maintenance. Ukulele creates and migrates it automagically.

**Comment by kiloforce** [comment]
BEAUTIFUL!  Thanks!
