### ISSUE TITLE
Feature Request: blacklist/whiltelist command (for Textchannels)

### ISSUE THREAD

**Issue by Baschdel-98** [Frederikam/ukulele#5]
Specify a list of textchannel where okulele should listen/take action when prefix is mentioned.
In case a user is trying to invoke okulele in a "disabled"/not approved channel, the bot could answer that this channel isn't supported. Aftert 5 sec the request and response could be deleted to keep the channels clean.

Only very vew discord music bots supports this feature.

I'm fairly new to discord bots and honestly don't know to implement that.

**Comment by OtterBoops** [comment]
You can restrict the bot via discord permissions. Not efficient stuffing a bunch of channel IDs in an embedded database.
