### ISSUE TITLE
Soundcloud support not working

### ISSUE THREAD

**Issue by Aasikki** [Frederikam/ukulele#9]
The bot seems to be working very well and reliably so far, the only current problem I have is that soundcloud support doesn't seem to be working as  I get "An exception occurred!
This url does not appear to be a playable track." when I try to play anything from soundcloud.

EDIT: Changed from "please add soundcloud support" to soundcloud support not working.

**Comment by Frederikam** [comment]
What makes you think Soundcloud is not supported? You should just be able to use a link.

**Comment by Frederikam** [comment]
Might be in need of a Lavaplayer update. Let me fix that

**Comment by Aasikki** [comment]
That did it. Almost can't believe how fast you responded and fixed it. Much thanks!
